name: Deploy test.txt via SCP

on:
  push:
    branches:
      - master  # Trigger bei Push auf den main-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Arbeitet auf einem Ubuntu-Linux-Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkt das Repository aus

      - name: Create test.txt
        run: |
          echo "Dies ist eine Testdatei" > test.txt  # Erstellt die Datei test.txt mit Inhalt

      - name: Copy test.txt to server via SCP
        uses: appleboy/scp-action@v0.1.0  # Nutzt die SCP-Action für den Transfer
        with:
          host: ${{ secrets.SERVER_HOST }}  # Der Server-Host (z.B. IP-Adresse oder Domainname)
          username: ${{ secrets.SERVER_USER }}  # Der SSH-Benutzername
          key: ${{ secrets.SERVER_SSH_KEY }}  # Der SSH-Schlüssel als Secret gespeichert
          port: 22  # Der SSH-Port (Standard ist 22)
          source: "test.txt"  # Die Quelle der Datei, die kopiert wird
          target: "/www/htdocs/w01ba8a0/wichtelgenerator"  # Zielverzeichnis auf dem Server
